spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          persistence-unit:
            eventStore:
              transaction-type: RESOURCE_LOCAL
              classes:
                - org.axonframework.eventsourcing.eventstore.jpa.DomainEventEntry
                - org.axonframework.eventsourcing.eventstore.jpa.SnapshotEventEntry
