# This is a basic workflow to help you get started with Actions

name: hello-jib build

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew jib
